export const HERO_THEMES = {
  default: {
    label       : "🌸 Everyday",
    badge       : "Fresh Daily · Local · Handcrafted",
    headline    : ["Flowers", "That Feel", "Like Home."],
    accentLine  : 1,
    sub         : "Handcrafted arrangements by Cecelia & Frank — cut fresh daily from our Piedmont studio and delivered across the Anniston area.",
    cta         : "Shop Arrangements",
    panelBg     : "#D4511A",
    panelEmoji  : "💐",
    floatingTags: ["✿ Fresh Cut", "✦ Same Day", "❋ Local Love"],
    start       : "2026-01-01T00:00:00Z",
    end         : "2026-02-01T00:00:00Z",
  },

  valentines: {
    label       : "❤️ Valentine's",
    badge       : "Valentine's Day · Feb 14th",
    headline    : ["Say It With", "Flowers", "This Feb 14."],
    accentLine  : 1,
    sub         : "Our Valentine's collection is here. Romantic arrangements, same-day delivery, and a handwritten note in every order.",
    cta         : "Shop Valentine's",
    panelBg     : "#751623",
    panelEmoji  : "🌹",
    floatingTags: ["❤️ Same Day", "✦ Feb 14th", "✿ Hand Tied"],
    start       : "2026-02-01T00:00:00Z",
    end         : "2026-02-15T00:00:00Z",
  },

  easter: {
    label       : "🐣 Easter",
    badge       : "Easter · Apr 5th",
    headline    : ["Fresh Blooms", "For a Bright", "Easter Table."],
    accentLine  : 1,
    sub         : "Celebrate Easter with soft pastels and fresh spring stems, arranged by hand and ready for your table.",
    cta         : "Shop Easter",
    panelBg     : "#F2C94C",
    panelEmoji  : "🐣",
    floatingTags: ["🐣 Spring", "✦ Pastels", "✿ Fresh"],
    start       : "2026-02-15T00:00:00Z",
    end         : "2026-04-06T00:00:00Z",
  },

  mothers: {
    label       : "💐 Mother's Day",
    badge       : "Mother's Day · May 10th",
    headline    : ["For the Woman", "Who Grew", "Everything."],
    accentLine  : 2,
    sub         : "Celebrate Mom with our most luxurious seasonal arrangements. Order early — our Mother's Day collection sells out fast.",
    cta         : "Shop Mother's Day",
    panelBg     : "#d63f94",
    panelEmoji  : "🌷",
    floatingTags: ["💐 For Mom", "✦ Sells Fast", "✿ Seasonal"],
    start       : "2026-04-06T00:00:00Z",
    end         : "2026-05-11T00:00:00Z",
  },

  graduation: {
    label       : "🎓 Graduation",
    badge       : "Graduation Season",
    headline    : ["Celebrate Their", "Big Moment", "With Flowers."],
    accentLine  : 1,
    sub         : "Bright, bold arrangements perfect for graduation celebrations and milestones.",
    cta         : "Shop Graduation",
    panelBg     : "#3A86FF",
    panelEmoji  : "🎓",
    floatingTags: ["🎓 Congrats", "✦ Bright", "✿ Seasonal"],
    start       : "2026-05-11T00:00:00Z",
    end         : "2026-06-01T00:00:00Z",
  },

  fathers: {
    label       : "👔 Father's Day",
    badge       : "Father's Day · Jun 21st",
    headline    : ["Strong, Simple,", "And Thoughtful", "For Dad."],
    accentLine  : 1,
    sub         : "Clean, modern arrangements and gifts designed with Dad in mind.",
    cta         : "Shop Father's Day",
    panelBg     : "#6C757D",
    panelEmoji  : "👔",
    floatingTags: ["👔 For Dad", "✦ Modern", "✿ Clean"],
    start       : "2026-06-01T00:00:00Z",
    end         : "2026-06-22T00:00:00Z",
  },

  independence: {
    label       : "🎆 Independence Day",
    badge       : "4th of July · Jul 4th",
    headline    : ["Celebrate Freedom", "With Bold", "Summer Blooms."],
    accentLine  : 1,
    sub         : "Red, white, and blue arrangements perfect for your Independence Day gatherings.",
    cta         : "Shop 4th of July",
    panelBg     : "#1D3557",
    panelEmoji  : "🎆",
    floatingTags: ["🎆 Summer", "✦ Bold", "✿ Festive"],
    start       : "2026-06-22T00:00:00Z",
    end         : "2026-07-05T00:00:00Z",
  },

  labor: {
    label       : "🛠️ Labor Day",
    badge       : "Labor Day · Sep 7th",
    headline    : ["End Summer", "With Something", "Beautiful."],
    accentLine  : 1,
    sub         : "Celebrate the long weekend with fresh arrangements and seasonal stems.",
    cta         : "Shop Labor Day",
    panelBg     : "#495057",
    panelEmoji  : "🛠️",
    floatingTags: ["🛠️ Weekend", "✦ Fresh", "✿ Seasonal"],
    start       : "2026-07-05T00:00:00Z",
    end         : "2026-09-08T00:00:00Z",
  },

  halloween: {
    label       : "🎃 Halloween",
    badge       : "Halloween · Oct 31st",
    headline    : ["Moody Blooms", "For a Spooky", "Season."],
    accentLine  : 1,
    sub         : "Dark tones, textured stems, and arrangements with a little mystery.",
    cta         : "Shop Halloween",
    panelBg     : "#6A040F",
    panelEmoji  : "🎃",
    floatingTags: ["🎃 Spooky", "✦ Moody", "✿ Unique"],
    start       : "2026-09-08T00:00:00Z",
    end         : "2026-11-01T00:00:00Z",
  },

  thanksgiving: {
    label       : "🦃 Thanksgiving",
    badge       : "Thanksgiving · Nov 26th",
    headline    : ["Gather Around", "The Table", "With Flowers."],
    accentLine  : 1,
    sub         : "Warm, rustic arrangements perfect for your Thanksgiving centerpiece.",
    cta         : "Shop Thanksgiving",
    panelBg     : "#7F5539",
    panelEmoji  : "🦃",
    floatingTags: ["🦃 Gather", "✦ Warm", "✿ Rustic"],
    start       : "2026-11-01T00:00:00Z",
    end         : "2026-11-27T00:00:00Z",
  },

  blackfriday: {
    label       : "🛍️ Black Friday",
    badge       : "Black Friday · Nov 27th",
    headline    : ["Big Deals", "For Your Favorite", "Arrangements."],
    accentLine  : 1,
    sub         : "Exclusive Black Friday discounts on seasonal bouquets and gifts.",
    cta         : "Shop Black Friday",
    panelBg     : "#FF6B6B",
    panelEmoji  : "🛍️",
    floatingTags: ["🛍️ Deals", "✦ Seasonal", "✿ Limited"],
    start       : "2026-11-27T00:00:00Z",
    end         : "2026-11-30T00:00:00Z",
  },

  cybermonday: {
    label       : "💻 Cyber Monday",
    badge       : "Cyber Monday · Nov 30th",
    headline    : ["Click & Save", "On Beautiful", "Blooms."],
    accentLine  : 1,
    sub         : "Special online-only deals for one day on arrangements and gifts.",
    cta         : "Shop Cyber Monday",
    panelBg     : "#0D6EFD",
    panelEmoji  : "💻",
    floatingTags: ["💻 Online", "✦ One Day", "✿ Deals"],
    start       : "2026-11-30T00:00:00Z",
    end         : "2026-12-01T00:00:00Z",
  },

  christmas: {
    label       : "🎄 Christmas",
    badge       : "Holiday Season · Dec 25th",
    headline    : ["Deck the Halls", "With Something", "Beautiful."],
    accentLine  : 2,
    sub         : "Seasonal wreaths, poinsettias, and festive arrangements — all made fresh at our Piedmont studio for the holiday table.",
    cta         : "Shop Holiday",
    panelBg     : "#1A3A2A",
    panelEmoji  : "🎄",
    floatingTags: ["🎄 Holiday", "✦ Wreaths", "✿ Seasonal"],
    start       : "2026-12-01T00:00:00Z",
    end         : "2026-12-26T00:00:00Z",
  },

  newyear: {
    label       : "🎆 New Year",
    badge       : "New Year's · Jan 1st",
    headline    : ["Ring In", "The New Year", "With Flowers."],
    accentLine  : 1,
    sub         : "Fresh arrangements and celebratory bouquets to start the year beautifully.",
    cta         : "Shop New Year",
    panelBg     : "#FFD700",
    panelEmoji  : "🎆",
    floatingTags: ["🎆 Celebration", "✦ Festive", "✿ Fresh Start"],
    start       : "2026-12-26T00:00:00Z",
    end         : "2027-01-01T23:59:59Z",
  }
};