export const HERO_THEMES = {
  default: {
    label       : "🌸 Everyday",
    badge       : "Local · Handcrafted",
    headline    : ["Treasure The Peices", " That Make You", ],
    accentLine  : null,
    sub         : "Every peice of your story matters - The hard ones, the healing ones, and everything in between",
    cta         : "Shop the Collection",
    panelBg     : "#e59393",
    panelEmoji  : "🌸",
    floatingTags: ["🌸 Handcrafted", "♻️ Refurbished", "✦ One of a Kind"],
    start       : "2026-01-01",
    end         : "2026-02-01",
  },

  valentines: {
    label       : "❤️ Valentine's",
    badge       : "Valentine's Day · Feb 14th",
    headline    : ["Give Something", "Made With", "Real Hands."],
    accentLine  : 2,
    sub         : "Skip the mass-produced gifts. Our Valentine's picks are handcrafted or thoughtfully restored — built with care, given with love.",
    cta         : "Shop Valentine's Finds",
    panelBg     : "#751623",
    panelEmoji  : "❤️",
    floatingTags: ["❤️ Handmade", "✦ Feb 14th", "♻️ Restored"],
    start       : "2026-02-01",
    end         : "2026-02-15",
  },

  easter: {
    label       : "🐣 Easter",
    badge       : "Easter · Apr 5th",
    headline    : ["Fresh Finds", "For a Brand", "New Season."],
    accentLine  : 1,
    sub         : "Spring into something special — hand-painted, handcrafted, or beautifully reclaimed goods ready for the season.",
    cta         : "Shop Easter Finds",
    panelBg     : "#4A7C59",
    panelEmoji  : "🐣",
    floatingTags: ["🐣 Spring", "✦ Hand-Painted", "♻️ Reclaimed"],
    start       : "2026-02-15",
    end         : "2026-04-06",
  },

  mothers: {
    label       : "💐 Mother's Day",
    badge       : "Mother's Day · May 10th",
    headline    : ["For the Woman", "Who Deserves", "Something Real."],
    accentLine  : 2,
    sub         : "Give Mom something made by hand or found with care — gifts that have a story and a soul, not a barcode.",
    cta         : "Shop Mother's Day",
    panelBg     : "#9B3A6E",
    panelEmoji  : "🎁",
    floatingTags: ["🎁 For Mom", "✦ Handcrafted", "♻️ One of a Kind"],
    start       : "2026-04-06",
    end         : "2026-05-11",
  },

  graduation: {
    label       : "🎓 Graduation",
    badge       : "Graduation Season",
    headline    : ["Start Fresh", "With Something", "Worth Keeping."],
    accentLine  : 1,
    sub         : "Celebrate the grad with handcrafted goods and reclaimed treasures that'll last longer than the diploma frame.",
    cta         : "Shop Graduation Gifts",
    panelBg     : "#2A6496",
    panelEmoji  : "🎓",
    floatingTags: ["🎓 Congrats", "✦ Lasting", "♻️ Reclaimed"],
    start       : "2026-05-11",
    end         : "2026-06-01",
  },

  fathers: {
    label       : "🪚 Father's Day",
    badge       : "Father's Day · Jun 21st",
    headline    : ["Built Tough,", "Found Cheap,", "Given With Love."],
    accentLine  : 1,
    sub         : "Dad will appreciate something real — reclaimed tools, handcrafted goods, and refurbished finds with real character.",
    cta         : "Shop Father's Day",
    panelBg     : "#4A4E54",
    panelEmoji  : "🪚",
    floatingTags: ["🪚 For Dad", "✦ Rugged", "♻️ Restored"],
    start       : "2026-06-01",
    end         : "2026-06-22",
  },

  independence: {
    label       : "🎆 Independence Day",
    badge       : "4th of July · Jul 4th",
    headline    : ["Independent", "Makers &", "American Finds."],
    accentLine  : 1,
    sub         : "Celebrate freedom and craftsmanship — handmade goods and reclaimed Americana pieces built by real hands.",
    cta         : "Shop 4th of July",
    panelBg     : "#1D3557",
    panelEmoji  : "🇺🇸",
    floatingTags: ["🇺🇸 American Made", "✦ Handcrafted", "♻️ Reclaimed"],
    start       : "2026-06-22",
    end         : "2026-07-05",
  },

  labor: {
    label       : "🛠️ Labor Day",
    badge       : "Labor Day · Sep 7th",
    headline    : ["Hard Work", "Makes the Best", "Things."],
    accentLine  : 1,
    sub         : "Labor Day weekend deals on handcrafted goods and refurbished finds — made or sourced by real hands.",
    cta         : "Shop Labor Day Deals",
    panelBg     : "#3D3D3D",
    panelEmoji  : "🛠️",
    floatingTags: ["🛠️ Weekend Deals", "✦ Handbuilt", "♻️ Restored"],
    start       : "2026-07-05",
    end         : "2026-09-08",
  },

  halloween: {
    label       : "🎃 Halloween",
    badge       : "Halloween · Oct 31st",
    headline    : ["Weird Finds,", "Spooky Goods,", "One of a Kind."],
    accentLine  : 1,
    sub         : "Upcycled oddities, handcrafted curiosities, and vintage finds with a little mystery — perfect for the season.",
    cta         : "Shop Halloween Finds",
    panelBg     : "#3D1A00",
    panelEmoji  : "🎃",
    floatingTags: ["🎃 Oddities", "✦ Vintage", "♻️ Upcycled"],
    start       : "2026-09-08",
    end         : "2026-11-01",
  },

  thanksgiving: {
    label       : "🦃 Thanksgiving",
    badge       : "Thanksgiving · Nov 26th",
    headline    : ["Tables Built", "By Hand,", "Gathered With Love."],
    accentLine  : 0,
    sub         : "Rustic handcrafted pieces and refurbished farmhouse finds — the kind of things that make a holiday table feel like home.",
    cta         : "Shop Thanksgiving",
    panelBg     : "#7F5539",
    panelEmoji  : "🦃",
    floatingTags: ["🦃 Rustic", "✦ Farmhouse", "♻️ Reclaimed"],
    start       : "2026-11-01",
    end         : "2026-11-27",
  },

  blackfriday: {
    label       : "🛍️ Black Friday",
    badge       : "Black Friday · Nov 27th",
    headline    : ["Big Deals On", "Handcrafted", "& Refurbished Finds."],
    accentLine  : 1,
    sub         : "Black Friday markdowns on our best handcrafted and refurbished pieces. One-of-a-kind stock — once it's gone, it's gone.",
    cta         : "Shop Black Friday",
    panelBg     : "#1A1A1A",
    panelEmoji  : "🛍️",
    floatingTags: ["🛍️ Limited Stock", "✦ One of a Kind", "♻️ Deals"],
    start       : "2026-11-27",
    end         : "2026-11-30",
  },

  cybermonday: {
    label       : "💻 Cyber Monday",
    badge       : "Cyber Monday · Nov 30th",
    headline    : ["Click, Claim,", "And Own Something", "Real."],
    accentLine  : 2,
    sub         : "Online-only Cyber Monday deals on handcrafted goods and refurbished finds. Every piece is one of a kind — don't wait.",
    cta         : "Shop Cyber Monday",
    panelBg     : "#0D6EFD",
    panelEmoji  : "💻",
    floatingTags: ["💻 Online Only", "✦ One Day", "♻️ Real Deals"],
    start       : "2026-11-30",
    end         : "2026-12-01",
  },

  christmas: {
    label       : "🎄 Christmas",
    badge       : "Holiday Season · Dec 25th",
    headline    : ["Gifts Made", "By Hand,", "Found With Love."],
    accentLine  : 0,
    sub         : "Give the gift of something real this holiday season — handcrafted pieces and lovingly restored finds for everyone on your list.",
    cta         : "Shop Holiday Gifts",
    panelBg     : "#1A3A2A",
    panelEmoji  : "🎄",
    floatingTags: ["🎄 Handcrafted", "✦ Restored", "♻️ One of a Kind"],
    start       : "2026-12-01",
    end         : "2026-12-26",
  },

  newyear: {
    label       : "🎆 New Year",
    badge       : "New Year's · Jan 1st",
    headline    : ["New Year,", "New Finds,", "Same Craftsmanship."],
    accentLine  : 1,
    sub         : "Ring in the new year with handcrafted goods and one-of-a-kind refurbished pieces — start fresh with something that lasts.",
    cta         : "Shop New Year Finds",
    panelBg     : "#8A6900",
    panelEmoji  : "🎆",
    floatingTags: ["🎆 Fresh Start", "✦ Handcrafted", "♻️ New Finds"],
    start       : "2026-12-26",
    end         : "2027-01-01",
  }
};
